# Broadcasting

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
result=arr**2
result

array([ 1,  4,  9, 16, 25])

In [3]:
result+10

array([11, 14, 19, 26, 35])

In [4]:
arr1=np.array([[12,23,34,56,67],[1,2,5,6,7]])
arr2=np.array([11,22,33,44,55])
result=arr1+arr2
result

array([[ 23,  45,  67, 100, 122],
       [ 12,  24,  38,  50,  62]])

# Built in mathematical function in numpy

In [5]:
arrr=np.array([10,20,30,40,50])
arrr

array([10, 20, 30, 40, 50])

In [6]:
np.mean(arrr)

30.0

In [7]:
np.std(arrr)

14.142135623730951

In [8]:
np.var(arrr)

200.0

In [9]:
np.min(arrr)

10

In [10]:
np.max(arrr)

50

In [11]:
np.sum(arrr)

150

In [12]:
np.prod(arrr)

12000000

In [13]:
np.median(arrr)

30.0

In [14]:
np.percentile(arrr,50)

30.0

In [15]:
np.argmin(arrr)

0

In [16]:
np.argmax(arrr)

4

In [17]:
np.unique(arrr)

array([10, 20, 30, 40, 50])

In [18]:
arrr1=np.array([60,70,80,90,100])

In [19]:
np.corrcoef(arrr,arrr1)

array([[1., 1.],
       [1., 1.]])

In [20]:
np.diff(arrr)

array([10, 10, 10, 10])

In [21]:
np.cumsum(arrr)

array([ 10,  30,  60, 100, 150])

In [22]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.log(arrr)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [24]:
np.exp(arrr)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])