# Creating numpy array

In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
arr.dtype

dtype('int32')

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.full((4,5),24)

array([[24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24],
       [24, 24, 24, 24, 24]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(1,50,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [13]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [14]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
myarr.shape

(4, 3)

In [16]:
myarr.ndim

2

In [17]:
myarr.dtype

dtype('int32')

In [22]:
myarr1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype="float32")

In [23]:
myarr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [24]:
myarr1.dtype

dtype('float32')

In [25]:
n=myarr1.astype("float64")

In [26]:
n.dtype

dtype('float64')

In [28]:
n

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [29]:
reshap=myarr1.reshape((2,6))

In [30]:
reshap

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]], dtype=float32)

In [31]:
myarr1.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
      dtype=float32)