# Indexing and Slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat=arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
flat[0]

1

In [6]:
flat[3:6]

array([4, 5, 6])

In [7]:
flat[:5]

array([1, 2, 3, 4, 5])

In [8]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
b=flat[3:7].copy()
b[1]=4444444
b

array([      4, 4444444,       6,       7])

In [11]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11, 12])